targets:
  _standalone_models:
   sources:
     - lib/src/models/episode.dart
     - lib/src/models/starship.dart
     - lib/src/models/character.dart
  $default:
   dependencies:
     - ":_standalone_models"
   sources:
     - lib/src/models/human.dart
     - lib/src/models/droid.dart
