name: star_wars
publish_to: none
dependencies:
  #angel_file_service: ^1.0.0
  angel_graphql: ^1.0.0
  angel_framework: ^2.0.1
  angel_hot: ^2.0.6
  angel_typed_service: ^1.0.1
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
  logging: ^0.11.3
  io: ^0.3.2
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  graphql_generator: ^1.0.0
  build_runner: ^1.0.0
